### ISSUE TITLE
Blocked by Age Verification Login

### ISSUE THREAD

**Issue by Bid-8888** [RedditDownloader/redditdownloader.github.io#13]
Seems there has been an update to Reddit that forces age verification (18+) for some subreddits (the interesting ones).
This downloader needs a way to insert credentials, or use generic ones in order to get to target.
As is, all downloads fail.

**Comment by Bid-8888** [comment]
There may be a way to use https//old.reddit.com  to avoid a login. It seems to only require age confirmation.

**Comment by alexanderhenne** [comment]
This looks like it's caused by allOrigins CORS proxy being down: https://github.com/gnuns/allOrigins/issues/112

I think we should wait a while and see if it comes up again and if not switch to a different proxy

**Comment by alexanderhenne** [comment]
The CORS proxy is up again. The downloader should work now
