### ISSUE TITLE
512 mb download limit

### ISSUE THREAD

**Issue by yanndonnard** [RedditDownloader/redditdownloader.github.io#5]
I'm unable to download more than 512mb of data for any users.
Maybe it's my browser...

**Comment by alexanderhenne** [comment]
Might just be the zipping of the downloaded items taking long? I added an info box which shows the progress now.

**Comment by yanndonnard** [comment]
> Might just be the zipping of the downloaded items taking long? I added an info box which shows the progress now.

It stuck like that :
![Screenshot 2021-08-31 at 16 09 42](https://user-images.githubusercontent.com/75851492/131518914-b0f2964a-b8ff-4625-b558-3edaebe42d0a.png)

**Comment by alexanderhenne** [comment]
Does this still happen?
