### ISSUE TITLE
Reddit downloader doesn't work

### ISSUE THREAD

**Issue by Nicsi19** [RedditDownloader/redditdownloader.github.io#7]
Hi, i've searched a lot but i didn't find any instructions how to make it work.

**Comment by Nicsi19** [comment]
It always says: "Retried retrieval of Reddit posts too many times, are you connected to the Internet?"

**Comment by Nicsi19** [comment]
https://github.com/RedditDownloader/redditdownloader.github.io/issues/6
Are there any news?

**Comment by alexanderhenne** [comment]
Fixed in #6
